export enum NotificationEvent {
    ADMIN_REGISTERED = "ADMIN_REGISTERED",
    COMPANY_APPROVED = "COMPANY_APPROVED",
    PAYMENT_RECEIVED = "PAYMENT_RECEIVED",
    SUBSCRIPTION_EXPIRING = "SUBSCRIPTION_EXPIRING",
}