export enum NotificationEvent {
    ADMIN_REGISTERED = "ADMIN_REGISTERED",
    ACCOUNT_STATUS_UPDATED = "ACCOUNT_STATUS_UPDATED",
    COMPANY_REGISTERED = "COMPANY_REGISTERED",
    COMPANY_STATUS_UPDATED = "COMPANY_STATUS_UPDATED",
    PAYMENT_RECEIVED = "PAYMENT_RECEIVED",
    SUBSCRIPTION_EXPIRING = "SUBSCRIPTION_EXPIRING",
}